/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
Input:
s = "abcd"
t = "abcde"

Output:
e

Solution: 
	- Use a Hashmap to store the characters in S and its count
	- Decrement the count for the characters in T
	- Return the character for which the count hits -1
 */

package hashmaps;

import java.util.HashMap;
import java.util.Map;

public class TwoStringDifference {
	public char findTheDifference(String s, String t) {
        Map<Character, Integer>map = new HashMap<Character, Integer>();
        for (char c: s.toCharArray()) {
    			map.put(c, map.getOrDefault(c,  0)+1);
        }
        for (char c: t.toCharArray()) {
        		map.put(c, map.getOrDefault(c,  0)-1);
        		if (map.get(c)==-1)
        			return c;
        }
        return '0';
    }
}
